/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package babygames;

/**
 *
 * @author aleja
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     * @param modal     
     */
    
    public PantallaPrincipal (boolean modal){
        super();
        initComponents();
    }
    
    public PantallaPrincipal() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        registrarse = new javax.swing.JButton();
        iniciarSesion = new javax.swing.JButton();
        salaMusical = new javax.swing.JButton();
        telefono = new javax.swing.JButton();
        canciones = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/babygames/imagenes/VENTANAPRINCIPAL (1).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 450));

        registrarse.setLabel("registrarse");
        getContentPane().add(registrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 110, -1));

        iniciarSesion.setText("jButton1");
        getContentPane().add(iniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, -1, 40));

        salaMusical.setText("jButton1");
        salaMusical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaMusicalActionPerformed(evt);
            }
        });
        getContentPane().add(salaMusical, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 193, 130, 140));

        telefono.setText("jButton1");
        getContentPane().add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 140, 130));

        canciones.setText("jButton1");
        getContentPane().add(canciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 140, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salaMusicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaMusicalActionPerformed
        // TODO add your handling code here:
        SalaMusicalPantalla sala = new SalaMusicalPantalla(this, true);
        sala.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_salaMusicalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton canciones;
    private javax.swing.JButton iniciarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton registrarse;
    private javax.swing.JButton salaMusical;
    private javax.swing.JButton telefono;
    // End of variables declaration//GEN-END:variables
}
